# 1C-D-04@R7 — unified portable Windows Debug test package
#
# One ZIP, one entry point, both PCs. Produces:
#
#   SayIt-Watch-0.3.0-dev.14-windows-wear-os-bundle.zip
#
# containing a Tauri **Debug** build whose frontend is EMBEDDED (`frontendDist`), so the
# unpacked application starts on any Windows PC without this source tree, without Node,
# without npm and without a Vite/localhost frontend server. The Debug receiver and its
# DNS-SD advertisement stay debug-only exactly as before.
#
# What this script does NOT do:
#   * it does not change firewall, network profile or any user configuration;
#   * it does not bundle, copy or generate a receiver config or a token;
#   * it does not stop, replace or uninstall any installed SayIt;
#   * it does not produce a release build, a release marker or an auto-update channel.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File client/scripts/package-watch-portable.ps1
#   powershell -ExecutionPolicy Bypass -File client/scripts/package-watch-portable.ps1 -SkipBuild

[CmdletBinding()]
param(
    # Reuse the already-built debug EXE instead of running cargo again.
    [switch]$SkipBuild,
    # Output directory for the ZIP (gitignored). Defaults to <repo>/dist-portable.
    [string]$OutputDir,
    # Explicit product commit to record in BUILD-INFO. Defaults to the current HEAD, which is
    # the bundle/Watch commit when the worktree is clean (the normal case).
    [string]$ProductCommit,
    # Commit that produced SayIt.exe. Normally this is the bundle commit. Supply an older commit
    # only with -SkipBuild after independently proving the desktop runtime sources are unchanged.
    [string]$WindowsBinaryCommit,
    # 1C-D-04@R9: generate ONLY the notes a real package would ship (README-PORTABLE.txt +
    # BUILD-INFO.txt) into -OutputDir, run the same static checks on them, and stop. It performs
    # no build, copies nothing and writes no ZIP, so a test can assert on the REAL generated
    # artefact instead of on a copy of the template inside this script.
    [switch]$NotesOnly
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$clientDir = Join-Path $repoRoot 'client'
$tauriDir = Join-Path $clientDir 'src-tauri'
if (-not $OutputDir) { $OutputDir = Join-Path $repoRoot 'dist-portable' }

$packageBase = 'SayIt-Watch-0.3.0-dev.14-windows-wear-os-bundle'
$zipPath = Join-Path $OutputDir "$packageBase.zip"
$stagingDir = Join-Path $OutputDir $packageBase

function Write-Step([string]$text) { Write-Host "==> $text" -ForegroundColor Cyan }
function Fail([string]$text) { Write-Host "ERROR: $text" -ForegroundColor Red; exit 1 }

# ── The shipped notes: ONE template, checked on the REAL generated bytes ──────
#
# The notes are written from a SINGLE-QUOTED here-string so nothing in them is interpreted: a
# backtick inside a double-quoted here-string is an escape character, and an earlier version
# silently shipped a form-feed where "frontendDist" should have been.
$receiverConfigRelative = '%LOCALAPPDATA%\com.sayit.app\watch-receiver.config.json'
# Notes are written as explicit UTF-8 (no BOM) so the bytes are deterministic on any Windows.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$buildInfoTemplate = @'
SayIt Watch Transport — unified Windows Debug test package
=========================================================

Package     : @PACKAGE@
Bundle/Watch: committed product head @GIT_HEAD@
Windows EXE : committed desktop-runtime head @WINDOWS_BINARY_COMMIT@
Build type  : Tauri Debug build with the frontend EMBEDDED in the executable.
Entry point : SayIt.exe  (same file on every PC — there is no per-PC package)
Watch app   : 0.3.0-dev.14 (versionCode 18), generic Wear OS 3+ compatibility contract

Quick install
-------------
1. Extract the complete folder. Do not run the app from inside the ZIP.
2. Double-click 1-Setup-PC.cmd. It selects an explicit private-LAN IPv4, creates or preserves
   the local token, writes the receiver config and starts SayIt.
3. Allow SayIt through Windows Firewall on Private networks only.
4. Put Android SDK platform-tools beside this folder (or add adb.exe to PATH), then double-click
   2-Install-Watch.cmd. It checks Wear OS 3+ / API 30+, watch form factor, microphone and Wi-Fi,
   guides pairing, installs SayIt-Watch.apk and provisions the same token on a first-time install.
5. Keep the PC and Watch on the same trusted Wi-Fi. Open Notepad, focus its input box, record on
   the Watch and stop; the recognized text should appear in the focused input box.

Why this is one package for every PC
------------------------------------
The frontend is compiled into SayIt.exe (the Tauri "frontendDist" setting), so the unpacked
application starts on its own. It does NOT need this source tree, Node, npm, Vite or a
localhost:1420/1421 frontend server. The Debug HTTP receiver and its DNS-SD advertisement are
unchanged and remain debug-only.

Connection details
------------------
The receiver configuration stays at:
    @RECEIVER_CONFIG@
1-Setup-PC.cmd writes an explicit RFC1918 address; it never recommends wildcard binding. If a
valid config already exists, it preserves the devToken field. For multiple PCs, you must bring the
token over yourself through a channel you trust and use the same token on every PC to be discovered.
The desktop still needs its own ASR/provider configuration; models and credentials are not copied.

What this package does NOT contain
----------------------------------
No configuration, no token or credential, no model file, no user history, no received audio,
no source tree, no node_modules, no installer, and no release/auto-update channel.

Current verification boundary
-----------------------------
Galaxy Watch 7 discovery, one real recording-to-text path, two-PC switching and the dev.13 picker
interactions have device evidence. The dev.14 generic compatibility contract is source/build
verified but still needs a non-Samsung Wear OS device run. Multi-PC recording routes,
repeated-run acceptance and a formal security Release remain incomplete. This is a Debug test
bundle, not a production installer.
'@

<#
  Writes the two shipped notes into $Directory.
  This is the ONLY place the shipped wording exists, so -NotesOnly (used by the unit tests) and a
  real package can never drift apart.
#>
function New-PortableNotes {
    param(
        [Parameter(Mandatory)][string]$Directory,
        [Parameter(Mandatory)][string]$ExeHash,
        [Parameter(Mandatory)][string]$GitHead,
        [Parameter(Mandatory)][string]$WindowsBinaryGitHead
    )
    $text = $buildInfoTemplate.
        Replace('@PACKAGE@', $packageBase).
        Replace('@GIT_HEAD@', $GitHead).
        Replace('@WINDOWS_BINARY_COMMIT@', $WindowsBinaryGitHead).
        Replace('@RECEIVER_CONFIG@', $receiverConfigRelative)
    [System.IO.File]::WriteAllText((Join-Path $Directory 'README-PORTABLE.txt'), $text, $utf8NoBom)

    # BUILD-INFO is assembled line by line (a here-string inside a function would have to escape
    # its own indentation). ASCII only, so PowerShell 5.1's encoding handling cannot change it.
    $versionLines = @(
        "package=$packageBase",
        'entry=SayIt.exe',
        'build=debug',
        'frontend=embedded',
        'watch=0.3.0-dev.14 (versionCode 18)',
        "git_head=$GitHead",
        "bundle_git_head=$GitHead",
        "watch_git_head=$GitHead",
        "windows_exe_git_head=$WindowsBinaryGitHead",
        "receiver_config=$receiverConfigRelative",
        "SayIt.exe.sha256=$ExeHash"
    )
    [System.IO.File]::WriteAllText(
        (Join-Path $Directory 'BUILD-INFO.txt'),
        (($versionLines -join "`r`n") + "`r`n"),
        $utf8NoBom
    )
}

<#
  The static gate on the GENERATED notes: plain text, correct paths, no control characters and no
  pointer at a settings entry that does not exist. It reads the artefacts, never the template, so
  it cannot pass on wording that was never shipped.
#>
function Test-PortableNotes {
    param(
        [Parameter(Mandatory)][string]$Directory,
        [Parameter(Mandatory)][string]$GitHead,
        [Parameter(Mandatory)][string]$WindowsBinaryGitHead
    )
    foreach ($noteName in @('README-PORTABLE.txt', 'BUILD-INFO.txt')) {
        $notePath = Join-Path $Directory $noteName
        if (-not (Test-Path $notePath)) { Fail "$noteName was not generated" }
        $noteBytes = [System.IO.File]::ReadAllBytes($notePath)
        foreach ($b in $noteBytes) {
            # Tab, LF and CR are the only control characters a text note may contain.
            if ($b -lt 0x20 -and $b -ne 0x09 -and $b -ne 0x0A -and $b -ne 0x0D) {
                Fail "$noteName contains a control character (0x$('{0:X2}' -f $b)); an escape was interpreted while generating it"
            }
        }
    }
    $readmeText = [System.IO.File]::ReadAllText((Join-Path $Directory 'README-PORTABLE.txt'), [System.Text.Encoding]::UTF8)
    # ASCII-only requirements: Windows PowerShell 5.1 cannot be trusted to round-trip a non-ASCII
    # literal through a BOM-less read, and a wrong encoding must not be able to pass this gate.
    foreach ($required in @(
        $receiverConfigRelative,
        'frontendDist',
        'SayIt.exe',
        'watch-receiver.config.json',
        'devToken',
        '1-Setup-PC.cmd',
        '2-Install-Watch.cmd',
        'SayIt-Watch.apk',
        'RFC1918',
        'Wear OS 3+',
        'API 30+',
        'microphone',
        'Wi-Fi'
    )) {
        if (-not $readmeText.Contains($required)) {
            Fail "README-PORTABLE.txt must mention $required"
        }
    }
    # The file must be valid UTF-8 (a garbled encoding would show up as a replacement character).
    if ($readmeText.Contains([char]0xFFFD)) {
        Fail 'README-PORTABLE.txt was not written as clean UTF-8'
    }
    if ($readmeText.Contains('"bindIp":"0.0.0.0"')) {
        Fail 'README-PORTABLE.txt must not recommend wildcard binding'
    }
    foreach ($forbidden in @('SayIt 设置', '服务器访问令牌')) {
        if ($readmeText.Contains($forbidden)) {
            Fail "README-PORTABLE.txt must not point at the non-existent destination $forbidden"
        }
    }
    $buildInfoText = [System.IO.File]::ReadAllText((Join-Path $Directory 'BUILD-INFO.txt'), [System.Text.Encoding]::UTF8)
    if (-not $buildInfoText.Contains("git_head=$GitHead")) {
        Fail 'BUILD-INFO.txt must record the product commit it was built from'
    }
    if (-not $buildInfoText.Contains("windows_exe_git_head=$WindowsBinaryGitHead")) {
        Fail 'BUILD-INFO.txt must record the commit that produced SayIt.exe'
    }
    if (-not $buildInfoText.Contains('frontend=embedded')) {
        Fail 'BUILD-INFO.txt must record that the frontend is embedded'
    }
}

# ── 0. Sanity: this must run from the R7/R8 worktree ───────────────────────────
if (-not (Test-Path (Join-Path $tauriDir 'tauri.conf.json'))) {
    Fail "client/src-tauri/tauri.conf.json not found under $repoRoot"
}

# The recorded product commit must be traceable. 1C-D-04@R8 P1: the package must be built from a
# CLEAN, COMMITTED product head, so `git rev-parse HEAD` really is the product commit and a dirty
# tree (uncommitted product source) can never be shipped under a hash that does not describe it.
function Invoke-GitValue([string[]]$arguments) {
    try {
        $output = & git -C $repoRoot @arguments 2>$null
        $exitCode = $LASTEXITCODE
        if ($exitCode -eq 0) {
            return [PSCustomObject]@{
                Success = $true
                Value = (($output | Out-String).Trim())
            }
        }
    } catch { }
    return [PSCustomObject]@{ Success = $false; Value = $null }
}

$gitStatusResult = Invoke-GitValue @('status', '--porcelain')
if (-not $gitStatusResult.Success) {
    Write-Host '   note: git is unavailable; the product commit cannot be verified' -ForegroundColor Yellow
    $dirty = $false
    $gitStatus = ''
} else {
    $gitStatus = $gitStatusResult.Value
    $dirty = $gitStatus.Length -gt 0
}
$headResult = Invoke-GitValue @('rev-parse', 'HEAD')
$baselineCommit = if ($ProductCommit) { $ProductCommit } elseif ($headResult.Success) { $headResult.Value } else { $null }
if (-not $baselineCommit) { $baselineCommit = 'unknown' }
$windowsCommit = if ($WindowsBinaryCommit) { $WindowsBinaryCommit } else { $baselineCommit }

# ── 1C-D-04@R9: -NotesOnly — generate the REAL notes and stop ─────────────────
# The unit tests must assert on the notes a package would really ship, not on a copy of the
# template inside this script. This mode writes them into -OutputDir, runs the SAME static gate the
# full package run uses, prints the paths and exits without building, copying or zipping anything.
# It deliberately runs BEFORE the clean-tree gate: generating notes cannot ship a binary, and a test
# has to be able to run it from a worktree that is still being edited.
if ($NotesOnly) {
    $notesDir = if ($OutputDir) { $OutputDir } else { Join-Path $repoRoot 'dist-portable\notes-preview' }
    if (-not (Test-Path $notesDir)) { New-Item -ItemType Directory -Path $notesDir -Force | Out-Null }
    Write-Step "Generating the shipped notes only (no build, no ZIP) into $notesDir"
    New-PortableNotes -Directory $notesDir -ExeHash 'not-built' -GitHead $baselineCommit -WindowsBinaryGitHead $windowsCommit
    Test-PortableNotes -Directory $notesDir -GitHead $baselineCommit -WindowsBinaryGitHead $windowsCommit
    Write-Host "NOTES-README=$notesDir\README-PORTABLE.txt"
    Write-Host "NOTES-BUILDINFO=$notesDir\BUILD-INFO.txt"
    Write-Host 'Notes-only run complete' -ForegroundColor Green
    exit 0
}

if ($dirty -and -not $SkipBuild) {
    Fail ("the worktree has uncommitted changes, so the package cannot record a product commit. " +
          "Commit the product work first, then build from the clean tree. (Dirty entries:`n$gitStatus)")
}
if ($dirty -and $SkipBuild) {
    Write-Host '   note: -SkipBuild was used with a dirty tree; BUILD-INFO still names the committed head' -ForegroundColor Yellow
}
if ($dirty -and $ProductCommit) {
    Write-Host "   note: worktree is dirty; BUILD-INFO names the explicitly supplied commit $ProductCommit" -ForegroundColor Yellow
}

$frontendDist = Join-Path $clientDir 'dist'
$watchApkPath = Join-Path $repoRoot 'watch\app\build\outputs\apk\debug\app-debug.apk'

# ── 1. Frontend: BUILD-TIME ONLY. The result is embedded in the EXE ────────────
if (-not $SkipBuild) {
    Write-Step 'Building the frontend (build-time only; the result is embedded in the EXE)'
    if (-not (Get-Command npm.cmd -ErrorAction SilentlyContinue) -and -not (Get-Command npm -ErrorAction SilentlyContinue)) {
        Fail 'npm is required to BUILD the package. It is not needed to RUN the packaged app.'
    }
    Push-Location $clientDir
    try {
        if (-not (Test-Path (Join-Path $clientDir 'node_modules'))) {
            Write-Host '   installing client dependencies (npm ci)'
            & npm.cmd ci --no-audit --no-fund
            if ($LASTEXITCODE -ne 0) { Fail "npm ci failed with exit code $LASTEXITCODE" }
        }
        & npm.cmd run build
        if ($LASTEXITCODE -ne 0) { Fail "frontend build failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }
}

if (-not (Test-Path (Join-Path $frontendDist 'index.html'))) {
    Fail "frontend dist is missing ($frontendDist). Run without -SkipBuild."
}
# The embedded frontend must contain the three windows' entries, otherwise the packaged
# app would start with a blank overlay/tray.
$requiredAssets = @('index.html', 'overlay.html', 'tray-menu.html')
foreach ($asset in $requiredAssets) {
    if (-not (Test-Path (Join-Path $frontendDist $asset))) {
        Fail "frontend dist is incomplete: $asset is missing"
    }
}

# ── 2. Debug binary (frontend embedded, Debug receiver retained) ───────────────
#
# The build command matters. A plain `cargo build` in a dev profile takes Tauri's DEV
# path (`devUrl` + the Vite dev server) and embeds NO frontend at all, so the packaged app
# would start blank. `tauri build --debug --no-bundle` produces a DEBUG binary with the
# production asset-embedding path and without packaging an installer.
$exePath = Join-Path $tauriDir 'target\debug\sayit.exe'
if (-not $SkipBuild) {
    Write-Step 'Building the Tauri Debug binary with the frontend embedded'

    # tauri-build does not declare the frontend dist as a rebuild input, so drop the
    # crate's own artifacts to guarantee a fresh embed.
    foreach ($artifact in @($exePath, (Join-Path $tauriDir 'target\debug\sayit.pdb'))) {
        if (Test-Path $artifact) { Remove-Item $artifact -Force }
    }

    $npx = Get-Command npx.cmd -ErrorAction SilentlyContinue
    if (-not $npx) { $npx = Get-Command npx -ErrorAction SilentlyContinue }
    if (-not $npx) { Fail 'npx is required to BUILD the package (it runs the Tauri CLI). It is not needed to RUN the packaged app.' }

    Push-Location $clientDir
    try {
        # `beforeBuildCommand` (npm run build) runs as part of this command, so the
        # frontend is regenerated and then embedded in the same step.
        & $npx.Source tauri build --debug --no-bundle
        if ($LASTEXITCODE -ne 0) { Fail "tauri build --debug failed with exit code $LASTEXITCODE" }
    } finally {
        Pop-Location
    }
}
if (-not (Test-Path $exePath)) { Fail "debug EXE not found at $exePath" }

# The embedded frontend must really be inside the binary, otherwise the packaged app
# starts with no UI at all while looking perfectly packaged.
Write-Step 'Verifying the frontend is embedded in the EXE'
$exeBytes = [System.IO.File]::ReadAllBytes($exePath)
$exeText = [System.Text.Encoding]::UTF8.GetString($exeBytes)
$embeddedCount = 0
foreach ($asset in (Get-ChildItem (Join-Path $frontendDist 'assets') -File -ErrorAction SilentlyContinue)) {
    if ($exeText.Contains($asset.Name)) { $embeddedCount++ }
}
if ($embeddedCount -eq 0) {
    Fail 'the built EXE embeds no frontend asset: it was produced by a dev-mode build (devUrl/Vite), not by `tauri build --debug`'
}
Write-Host "   embedded frontend assets found in the EXE: $embeddedCount"

# A release binary must never be shipped through this path.
$releaseExe = Join-Path $tauriDir 'target\release\sayit.exe'
if ((Test-Path $releaseExe) -and ((Get-Item $releaseExe).LastWriteTimeUtc -gt (Get-Item $exePath).LastWriteTimeUtc)) {
    Write-Host '   note: a newer release EXE exists; this package still uses the Debug one' -ForegroundColor Yellow
}

# ── 3. Stage the package ──────────────────────────────────────────────────────
Write-Step "Staging $stagingDir"
if (Test-Path $stagingDir) { Remove-Item $stagingDir -Recurse -Force }
New-Item -ItemType Directory -Path $stagingDir -Force | Out-Null

Copy-Item $exePath (Join-Path $stagingDir 'SayIt.exe') -Force

if (-not (Test-Path -LiteralPath $watchApkPath)) {
    Fail 'Watch Debug APK is missing. Build watch/app assembleDebug before packaging.'
}
Copy-Item $watchApkPath (Join-Path $stagingDir 'SayIt-Watch.apk') -Force

foreach ($helper in @(
    '1-Setup-PC.cmd',
    '2-Install-Watch.cmd',
    'Setup-PC.ps1',
    'Install-Watch.ps1'
)) {
    $source = Join-Path $PSScriptRoot $helper
    if (-not (Test-Path -LiteralPath $source)) { Fail "setup helper is missing: $helper" }
    Copy-Item $source (Join-Path $stagingDir $helper) -Force
}

# Runtime libraries the app loads next to itself: the transcribe/ggml backend DLLs the
# build staged, plus any MSVC runtime DLL the toolchain copied beside the EXE.
$dllSources = @(
    (Join-Path $tauriDir 'transcribe-libs'),
    (Join-Path $tauriDir 'target\debug')
)
$dllCount = 0
foreach ($dir in $dllSources) {
    if (-not (Test-Path $dir)) { continue }
    Get-ChildItem $dir -Filter *.dll -File | ForEach-Object {
        $target = Join-Path $stagingDir $_.Name
        if (-not (Test-Path $target)) { Copy-Item $_.FullName $target -Force; $dllCount++ }
    }
}

# Bundled app resources (Tauri `bundle.resources`: resources/* and transcribe-libs/*).
$resourceDir = Join-Path $tauriDir 'resources'
if (Test-Path $resourceDir) {
    $stagedResources = Join-Path $stagingDir 'resources'
    New-Item -ItemType Directory -Path $stagedResources -Force | Out-Null
    Copy-Item (Join-Path $resourceDir '*') $stagedResources -Force -Recurse
}

# ── 4. Version / baseline / usage notes ───────────────────────────────────────
$exeHash = (Get-FileHash (Join-Path $stagingDir 'SayIt.exe') -Algorithm SHA256).Hash.ToLowerInvariant()

# 1C-D-04@R9: the shipped notes come from the ONE template inside New-PortableNotes, so a real
# package and the -NotesOnly gate the unit tests run can never drift apart.
New-PortableNotes -Directory $stagingDir -ExeHash $exeHash -GitHead $baselineCommit -WindowsBinaryGitHead $windowsCommit

# ── 5. SHA256SUMS over the payload (not over itself) ──────────────────────────
Write-Step 'Computing SHA256SUMS'
$payload = Get-ChildItem $stagingDir -Recurse -File |
    Where-Object { $_.Name -ne 'SHA256SUMS' } |
    Sort-Object FullName
$lines = foreach ($file in $payload) {
    $relative = $file.FullName.Substring($stagingDir.Length + 1).Replace('\', '/')
    $hash = (Get-FileHash $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    "$hash  $relative"
}
[System.IO.File]::WriteAllText((Join-Path $stagingDir 'SHA256SUMS'), ($lines -join "`n"), $utf8NoBom)

# The notes are read by a human on a machine that has nothing else, so they must be plain text,
# name the real configuration path, and never contain an interpreted escape that turned into a
# control character while the package was generated. The SAME gate runs in -NotesOnly mode, so
# it cannot be satisfied by wording that was never generated.
Write-Step 'Checking the generated notes (text, path, no control characters)'
Test-PortableNotes -Directory $stagingDir -GitHead $baselineCommit -WindowsBinaryGitHead $windowsCommit

# ── 6. ZIP ────────────────────────────────────────────────────────────────────
Write-Step "Creating $zipPath"
if (-not (Test-Path $OutputDir)) { New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null }
if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
Add-Type -AssemblyName System.IO.Compression.FileSystem
[System.IO.Compression.ZipFile]::CreateFromDirectory(
    $stagingDir,
    $zipPath,
    [System.IO.Compression.CompressionLevel]::Optimal,
    $true # include the package folder as the archive's single root
)

$zipHash = (Get-FileHash $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()
$zipSize = (Get-Item $zipPath).Length

Write-Host ''
Write-Host 'Package ready' -ForegroundColor Green
Write-Host "  ZIP         : $zipPath"
Write-Host "  ZIP SHA-256 : $zipHash"
Write-Host "  ZIP bytes   : $zipSize"
Write-Host "  EXE SHA-256 : $exeHash"
Write-Host "  DLLs staged : $dllCount"
Write-Host "  git HEAD    : $baselineCommit"
Write-Host ''
Write-Host 'Independent startup smoke check (no source tree, no Node):'
Write-Host "  1. Expand-Archive '$zipPath' -DestinationPath <empty-temp-dir>"
Write-Host "  2. run <empty-temp-dir>\$packageBase\SayIt.exe from that directory"
Write-Host '  3. confirm the app window/overlay/tray work and no localhost frontend is needed'
